### PR TITLE
extracted timezone env from composers  into .env file

### PR DESCRIPTION
**Pull request by atipezda**
That changes allows user to change timezone quickly in .env file and also it standardize same timezone across all containers

### CODE REVIEW

**Comment by bscheshirwork** [comment]
Thank you for contribution. Add default value of TZ for back compatibility please.

**Comment by atipezda** [comment]
Hi, what do You mean by default value of TZ. I thought that `TZ=Europe/Moscow` in `.env_example` file is enough. I must point out that I'm new into open-source contributing so I'm still learning 😄

**Comment by bscheshirwork** [comment]
I tell about this case:
- I already have composition
- I already have copy of .env_example
- I pull new changes
- I have empty TZ instead of old value 'Europe/Moscow'

I think we need this
```
    environment:
￼      TZ: "${TZ:-Europe/Moscow}"
```
Can you check how to work it please?

see https://github.com/docker/docker.github.io/issues/6914#issuecomment-398818071

**Comment by atipezda** [comment]
Oh okay i didn't know about default variables in docker envs. I will edit the pr tommorow

**Comment by atipezda** [comment]
> Thank you for contribution. Add default value of TZ for back compatibility please.

Done in  [https://github.com/bscheshirwork/docker-yii2-app-advanced/pull/4/commits/33c97ae26d1b9ca59c0f70fe1c4962f336f35849](url) and [https://github.com/bscheshirwork/docker-yii2-app-advanced/pull/4/commits/551dd9f5169a52d60f730e40aaafc70668b2ca65](url)

**Comment by atipezda** [comment]
> Thank you for contribution. Add default value of TZ for back compatibility please.

Done.

**Comment by bscheshirwork** [comment]
Thank you!

**Pull request merged**
