### PR TITLE
Correcting mistakes in instructions

### PR DESCRIPTION
**Pull request by viktorprogger**
Hi! I've corrected some mistakes in .md files. But I didn't understand what did you mean with 

> For test used another base, but the same named service `db` (and the same connect string)

Can you write it in russian or in english but in another words for me to correct this too?

### CODE REVIEW

**Comment by viktorprogger** [comment]
I still didn't finish this work: I need to work a little now :)

**Comment by bscheshirwork** [comment]
> For test used another base, but the same named service db (and the same connect string)

For test case we can used another MySQL engine folder "mysql-data-test", but the same named docker service "db" (and the same connect string in yii local config)

**Comment by viktorprogger** [comment]
Thanks. I'll try to finish today.

**Comment by viktorprogger** [comment]
Sorry for waiting so long. I've finished now :)

Please check if new texts don't conflict with the originally embedded meaning.

**Comment by bscheshirwork** [comment]
Looks fine for me. Thank you!

**Pull request merged**
